/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condominium;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

/**
 *
 * @author BoomGDH559
 */
public class Condominium extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Condominium() {
        initComponents();
        register.setVisible(false);
        adIndex.setVisible(false);
        firstname.setBackground(new Color(0, 0, 0, 0));
        lastname.setBackground(new Color(0, 0, 0, 0));
        usertype.setBackground(new Color(0, 0, 0, 0));
        usertel.setBackground(new Color(0, 0, 0, 0));
        userregis.setBackground(new Color(0, 0, 0, 0));
        useremerg.setBackground(new Color(0, 0, 0, 0));
        userId.setBackground(new Color(0, 0, 0, 0));
        userpass.setBackground(new Color(0, 0, 0, 0));
        usernation.setBackground(new Color(0, 0, 0, 0));
        email.setBackground(new Color(0, 0, 0, 0));
        userpass.setBackground(new Color(0, 0, 0, 0));
        usertype.setBackground(new Color(0, 0, 0, 0));
        regisbut.setBackground(new Color(0, 0, 0, 0));
        home.setBackground(new Color(0, 0, 0, 0));
        save.setBackground(new Color(0, 0, 0, 0));
        clear.setBackground(new Color(0, 0, 0, 0));
        register1.setBackground(new Color(0, 0, 0, 0));
        report.setBackground(new Color(0, 0, 0, 0));
        status.setBackground(new Color(0, 0, 0, 0));
        login.setBackground(new Color(0, 0, 0, 0));
        password.setBackground(new Color(0, 0, 0, 0));
        password.setEchoChar('•');
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        date = new com.toedter.calendar.JDateChooser();
        lastname = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        userId = new javax.swing.JTextField();
        usertel = new javax.swing.JTextField();
        usernation = new javax.swing.JTextField();
        useremerg = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        userregis = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        usertype = new javax.swing.JComboBox<>();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        userpass = new javax.swing.JPasswordField();
        report = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        adIndex = new javax.swing.JPanel();
        regisbut = new javax.swing.JButton();
        adminIndexbg = new javax.swing.JLabel();
        register1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 600));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setBackground(new Color(0,0,0,0));
        username.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 204, 204));
        username.setCaretColor(new java.awt.Color(238, 218, 209));
        username.setSelectedTextColor(new java.awt.Color(238, 218, 209));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        Login.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 260, -1));

        status.setEditable(false);
        status.setFont(new java.awt.Font("DB Helvethaica X 55 Regular", 1, 24)); // NOI18N
        status.setForeground(new java.awt.Color(255, 170, 171));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        Login.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 320, 30));

        password.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 36)); // NOI18N
        password.setForeground(new java.awt.Color(255, 171, 172));
        Login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 552, 260, 30));

        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        Login.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 140, 40));

        Background.setForeground(new java.awt.Color(238, 218, 209));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominium/gui-ex.png"))); // NOI18N
        Background.setText("jLabel1");
        Background.setPreferredSize(new java.awt.Dimension(750, 600));
        Login.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        register.setMinimumSize(new java.awt.Dimension(750, 600));
        register.setPreferredSize(new java.awt.Dimension(750, 600));
        register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        register.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 160, -1));

        lastname.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 130, 30));

        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        register.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 80));

        userId.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(userId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 150, 30));

        usertel.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(usertel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 150, 30));

        usernation.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(usernation, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 110, 30));

        useremerg.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(useremerg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 150, 30));

        email.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 180, 30));

        userregis.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(userregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 130, 30));

        firstname.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, 30));

        usertype.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ระบุ user", "user", "admin" }));
        usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertypeActionPerformed(evt);
            }
        });
        register.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 120, 30));
        register.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 100, 40));
        register.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 100, 40));

        userpass.setFont(new java.awt.Font("DB Helvethaica X 45 Li", 1, 24)); // NOI18N
        register.add(userpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 150, -1));
        register.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 70, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("DB Helvethaica X 55 Regular", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        register.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 470, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominium/register.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(750, 600));
        register.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        adIndex.setPreferredSize(new java.awt.Dimension(750, 600));
        adIndex.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regisbut.setPreferredSize(new java.awt.Dimension(224, 431));
        regisbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisbutActionPerformed(evt);
            }
        });
        adIndex.add(regisbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, 440));

        adminIndexbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominium/Admin-index.png"))); // NOI18N
        adminIndexbg.setText("jLabel2");
        adIndex.add(adminIndexbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        register1.setContentAreaFilled(false);
        register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register1ActionPerformed(evt);
            }
        });
        adIndex.add(register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 70, 30));

        getContentPane().add(adIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertypeActionPerformed

    private void regisbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisbutActionPerformed
        adIndex.setVisible(false);
        register.setVisible(true);
    }//GEN-LAST:event_regisbutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        adIndex.setVisible(true);
        register.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register1ActionPerformed
        adIndex.setVisible(false);
        register.setVisible(true);
    }//GEN-LAST:event_register1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        //
    }//GEN-LAST:event_usernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String user = username.getText();
        char[] word = password.getPassword();
        String pass = new String(word);
        System.out.println("User : "+user);
        System.out.println("Pass : "+pass);
        if (!(user.equals("")&& pass.equals(""))) {
            if (user.equalsIgnoreCase("Boom") && (pass.equalsIgnoreCase("Purich1998"))) {
                adIndex.setVisible(true);
                Login.setVisible(false);

            } else {
                String st = "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง";
                status.setText(st);
            }
        }else{
            String st = "กรุณาระบุชื่อผู้ใช้";
            status.setText(st);
        }

    }//GEN-LAST:event_loginActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        //
    }//GEN-LAST:event_statusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Condominium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Condominium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Condominium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Condominium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Condominium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel adIndex;
    private javax.swing.JLabel adminIndexbg;
    private javax.swing.JButton clear;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton regisbut;
    private javax.swing.JPanel register;
    private javax.swing.JButton register1;
    private javax.swing.JButton report;
    private javax.swing.JButton save;
    private javax.swing.JTextField status;
    private javax.swing.JTextField userId;
    private javax.swing.JTextField useremerg;
    private javax.swing.JTextField username;
    private javax.swing.JTextField usernation;
    private javax.swing.JPasswordField userpass;
    private javax.swing.JTextField userregis;
    private javax.swing.JTextField usertel;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables
}
